version: 2.1
jobs:
  create:
    working_directory: ~/circleci-armadillo
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          CONAN_NON_INTERACTIVE: true
    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          keys:
            - pipenv-v1-{{ checksum "Pipfile.lock" }}
            - pipenv-v1-

      - run: sudo pip install pipenv

      - run: pipenv clean
      - run: pipenv install --dev

      - save_cache:
          key: pipenv-v1-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      - restore_cache:
          keys:
            - conan-v1-{{ checksum "conanfile.py" }}
            - conan-v1-

      - run:
          name: Create
          command: pipenv run conan create .
      - run:
          name: Cross-build android arm64-v8a abi
          command: pipenv run conan create . --profile ./profiles/android-arm64-v8a --build missing

      - save_cache:
          key: conan-v1-{{ checksum "conanfile.py" }}
          paths:
            - "~/.conan/data/android_ndk_installer"
            - "~/.conan/data/openblas"
            - "~/.conan/data/pkg-config_installer"

  push-recipe:
    working_directory: ~/circleci-armadillo
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          CONAN_NON_INTERACTIVE: true
    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          keys:
            - v1-{{ checksum "Pipfile.lock" }}
            - v1-

      - run: sudo pip install pipenv

      - run: pipenv clean
      - run: pipenv install --dev

      - save_cache:
          key: v1-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      - run:
          name: Login
          command: |
            pipenv run conan remote add polars-org-remote https://api.bintray.com/conan/polarsorg/Polars
            pipenv run conan user -p $CONAN_API_KEY -r polars-org-remote $CONAN_LOGIN_USERNAME

      - run:
          name: Upload recipe
          command: |
            pipenv run conan export .
            pipenv run conan upload -r polars-org-remote --confirm Armadillo/*

workflows:
  version: 2
  main:
    jobs:
      - create
      - push-recipe:
          context: bintray-machine-user
          requires:
            - create
          filters:
            branches:
              only: master
